---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git
  pull: default
  image: plugins/git
  settings:
    depth: 50
    tags: true

- name: test
  pull: always
  image: golang:1.11
  environment:
    GO111MODULE: on
  commands:
  - make vet
  - make lint
  - make embedmd
  - make test

- name: codecov
  pull: default
  image: plugins/codecov
  settings:
    pattern: "**/coverage.txt"
  environment:
    CODECOV_TOKEN:
      from_secret: codecov_token

- name: discord
  pull: always
  image: appleboy/drone-discord
  environment:
    DISCORD_WEBHOOK_ID:
      from_secret: discord_webhook_id
    DISCORD_WEBHOOK_TOKEN:
      from_secret: discord_webhook_token
  when:
    status:
    - success
    - failure

...
